package net.ada.mixins;

import net.ada.Client;
import net.minecraft.client.Minecraft;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(Minecraft.class)
public class MinecraftMixin {
    @Inject(method = "run", at = @At("HEAD"))
    private void onInitialize(CallbackInfo ci) {
        System.out.println(">>> MINECRAFT HAS STARTED! <<<");

        Client client = new Client();

        var test = client.getClientAPI().getWebGUIPlatform().generateGUIObject("test");

        test.setCSSComponent(
                "#dragBox {\n"
                        + "    --panel-rgb: 79, 70, 229;\n"
                        + "    --panel-opacity: 0.65;\n"
                        + "    --panel-blur: 16px;\n"
                        + "    position: absolute;\n"
                        + "    left: 100px;\n"
                        + "    top: 100px;\n"
                        + "    width: 280px;\n"
                        + "    max-height: min(480px, calc(100vh - 20px));\n"
                        + "    overflow: hidden;\n"
                        + "    color: white;\n"
                        + "    background: rgba(var(--panel-rgb), var(--panel-opacity));\n"
                        + "    border: 1px solid rgba(255, 255, 255, 0.3);\n"
                        + "    border-radius: 14px;\n"
                        + "    box-shadow: 0 16px 40px rgba(0, 0, 0, 0.4);\n"
                        + "    backdrop-filter: blur(var(--panel-blur));\n"
                        + "    -webkit-backdrop-filter: blur(var(--panel-blur));\n"
                        + "    pointer-events: auto;\n"
                        + "    font-family: Arial, sans-serif;\n"
                        + "}\n"
                        + "\n"
                        + "#dragHandle {\n"
                        + "    padding: 14px 16px;\n"
                        + "    font-weight: bold;\n"
                        + "    cursor: grab;\n"
                        + "    user-select: none;\n"
                        + "    touch-action: none;\n"
                        + "    border-bottom: 1px solid rgba(255, 255, 255, 0.25);\n"
                        + "}\n"
                        + "\n"
                        + "#dragHandle:active {\n"
                        + "    cursor: grabbing;\n"
                        + "}\n"
                        + "\n"
                        + ".panelContent {\n"
                        + "    display: flex;\n"
                        + "    flex-direction: column;\n"
                        + "    gap: 10px;\n"
                        + "    max-height: 390px;\n"
                        + "    padding: 16px;\n"
                        + "    overflow-y: auto;\n"
                        + "    scrollbar-width: thin;\n"
                        + "    scrollbar-color: rgba(255, 255, 255, 0.8) rgba(0, 0, 0, 0.2);\n"
                        + "}\n"
                        + "\n"
                        + ".panelContent::-webkit-scrollbar {\n"
                        + "    width: 9px;\n"
                        + "}\n"
                        + "\n"
                        + ".panelContent::-webkit-scrollbar-track {\n"
                        + "    background: rgba(0, 0, 0, 0.2);\n"
                        + "    border-radius: 10px;\n"
                        + "}\n"
                        + "\n"
                        + ".panelContent::-webkit-scrollbar-thumb {\n"
                        + "    background: rgba(255, 255, 255, 0.75);\n"
                        + "    border-radius: 10px;\n"
                        + "}\n"
                        + "\n"
                        + ".panelContent label {\n"
                        + "    font-size: 13px;\n"
                        + "    font-weight: bold;\n"
                        + "}\n"
                        + "\n"
                        + "#textInput {\n"
                        + "    box-sizing: border-box;\n"
                        + "    width: 100%;\n"
                        + "    padding: 10px;\n"
                        + "    color: white;\n"
                        + "    background: rgba(0, 0, 0, 0.25);\n"
                        + "    border: 1px solid rgba(255, 255, 255, 0.35);\n"
                        + "    border-radius: 8px;\n"
                        + "    outline: none;\n"
                        + "}\n"
                        + "\n"
                        + "#textInput::placeholder {\n"
                        + "    color: rgba(255, 255, 255, 0.7);\n"
                        + "}\n"
                        + "\n"
                        + "#textInput:focus {\n"
                        + "    border-color: white;\n"
                        + "}\n"
                        + "\n"
                        + "#myButton {\n"
                        + "    padding: 10px 14px;\n"
                        + "    color: #111827;\n"
                        + "    font-weight: bold;\n"
                        + "    background: rgba(255, 255, 255, 0.9);\n"
                        + "    border: 0;\n"
                        + "    border-radius: 8px;\n"
                        + "    cursor: pointer;\n"
                        + "}\n"
                        + "\n"
                        + "#myButton:hover {\n"
                        + "    background: white;\n"
                        + "}\n"
                        + "\n"
                        + "input[type=\"range\"] {\n"
                        + "    width: 100%;\n"
                        + "    accent-color: white;\n"
                        + "    cursor: pointer;\n"
                        + "}\n"
                        + "\n"
                        + ".exampleText {\n"
                        + "    min-height: 90px;\n"
                        + "    padding: 10px;\n"
                        + "    font-size: 13px;\n"
                        + "    line-height: 1.5;\n"
                        + "    background: rgba(0, 0, 0, 0.18);\n"
                        + "    border-radius: 8px;\n"
                        + "}\n"
                        + "\n"
                        + "#palette {\n"
                        + "    display: grid;\n"
                        + "    grid-template-columns: repeat(6, 1fr);\n"
                        + "    gap: 8px;\n"
                        + "    padding-top: 12px;\n"
                        + "    border-top: 1px solid rgba(255, 255, 255, 0.25);\n"
                        + "}\n"
                        + "\n"
                        + "#palette .color {\n"
                        + "    aspect-ratio: 1;\n"
                        + "    min-width: 0;\n"
                        + "    margin: 0;\n"
                        + "    padding: 0;\n"
                        + "    background: var(--swatch);\n"
                        + "    border: 2px solid rgba(255, 255, 255, 0.35);\n"
                        + "    border-radius: 50%;\n"
                        + "    cursor: pointer;\n"
                        + "}\n"
                        + "\n"
                        + "#palette .color:hover {\n"
                        + "    transform: scale(1.12);\n"
                        + "}\n"
                        + "\n"
                        + "#palette .color.active {\n"
                        + "    border-color: white;\n"
                        + "    box-shadow: 0 0 0 2px rgba(0, 0, 0, 0.35);\n"
                        + "}\n");
        test.setJSComponent("(function () {\n"
                + "    function initializePanel() {\n"
                + "        var box = document.getElementById(\"dragBox\");\n"
                + "        var handle = document.getElementById(\"dragHandle\");\n"
                + "        var button = document.getElementById(\"myButton\");\n"
                + "        var textInput = document.getElementById(\"textInput\");\n"
                + "        var opacitySlider = document.getElementById(\"opacitySlider\");\n"
                + "        var opacityValue = document.getElementById(\"opacityValue\");\n"
                + "        var blurSlider = document.getElementById(\"blurSlider\");\n"
                + "        var blurValue = document.getElementById(\"blurValue\");\n"
                + "        var colors = document.querySelectorAll(\"#palette .color\");\n"
                + "\n"
                + "        if (!box || !handle) {\n"
                + "            return;\n"
                + "        }\n"
                + "\n"
                + "        var dragging = false;\n"
                + "        var offsetX = 0;\n"
                + "        var offsetY = 0;\n"
                + "\n"
                + "        handle.addEventListener(\"pointerdown\", function (event) {\n"
                + "            event.preventDefault();\n"
                + "            event.stopPropagation();\n"
                + "\n"
                + "            if (document.pointerLockElement && document.exitPointerLock) {\n"
                + "                document.exitPointerLock();\n"
                + "            }\n"
                + "\n"
                + "            var rect = box.getBoundingClientRect();\n"
                + "            dragging = true;\n"
                + "            offsetX = event.clientX - rect.left;\n"
                + "            offsetY = event.clientY - rect.top;\n"
                + "\n"
                + "            if (handle.setPointerCapture) {\n"
                + "                handle.setPointerCapture(event.pointerId);\n"
                + "            }\n"
                + "        });\n"
                + "\n"
                + "        handle.addEventListener(\"pointermove\", function (event) {\n"
                + "            if (!dragging) {\n"
                + "                return;\n"
                + "            }\n"
                + "\n"
                + "            event.preventDefault();\n"
                + "            event.stopPropagation();\n"
                + "\n"
                + "            var maxX = Math.max(0, window.innerWidth - box.offsetWidth);\n"
                + "            var maxY = Math.max(0, window.innerHeight - box.offsetHeight);\n"
                + "            var x = Math.max(0, Math.min(event.clientX - offsetX, maxX));\n"
                + "            var y = Math.max(0, Math.min(event.clientY - offsetY, maxY));\n"
                + "\n"
                + "            box.style.left = x + \"px\";\n"
                + "            box.style.top = y + \"px\";\n"
                + "        });\n"
                + "\n"
                + "        function stopDragging(event) {\n"
                + "            dragging = false;\n"
                + "\n"
                + "            if (handle.hasPointerCapture &&\n"
                + "                handle.hasPointerCapture(event.pointerId)) {\n"
                + "                handle.releasePointerCapture(event.pointerId);\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "        handle.addEventListener(\"pointerup\", stopDragging);\n"
                + "        handle.addEventListener(\"pointercancel\", stopDragging);\n"
                + "\n"
                + "        opacitySlider.addEventListener(\"input\", function () {\n"
                + "            var opacity = Number(opacitySlider.value);\n"
                + "            box.style.setProperty(\"--panel-opacity\", opacity / 100);\n"
                + "            opacityValue.textContent = opacity + \"%\";\n"
                + "        });\n"
                + "\n"
                + "        blurSlider.addEventListener(\"input\", function () {\n"
                + "            var blur = Number(blurSlider.value);\n"
                + "            box.style.setProperty(\"--panel-blur\", blur + \"px\");\n"
                + "            blurValue.textContent = blur + \"px\";\n"
                + "        });\n"
                + "\n"
                + "        function hexToRgb(hex) {\n"
                + "            var value = hex.replace(\"#\", \"\");\n"
                + "\n"
                + "            return {\n"
                + "                r: parseInt(value.substring(0, 2), 16),\n"
                + "                g: parseInt(value.substring(2, 4), 16),\n"
                + "                b: parseInt(value.substring(4, 6), 16)\n"
                + "            };\n"
                + "        }\n"
                + "\n"
                + "        for (var i = 0; i < colors.length; i++) {\n"
                + "            colors[i].addEventListener(\"click\", function () {\n"
                + "                var rgb = hexToRgb(this.getAttribute(\"data-color\"));\n"
                + "\n"
                + "                box.style.setProperty(\n"
                + "                    \"--panel-rgb\",\n"
                + "                    rgb.r + \", \" + rgb.g + \", \" + rgb.b\n"
                + "                );\n"
                + "\n"
                + "                for (var j = 0; j < colors.length; j++) {\n"
                + "                    colors[j].classList.remove(\"active\");\n"
                + "                }\n"
                + "\n"
                + "                this.classList.add(\"active\");\n"
                + "            });\n"
                + "        }\n"
                + "\n"
                + "        button.addEventListener(\"click\", function () {\n"
                + "            alert(textInput.value || \"Button clicked!\");\n"
                + "        });\n"
                + "    }\n"
                + "\n"
                + "    if (document.readyState === \"loading\") {\n"
                + "        document.addEventListener(\"DOMContentLoaded\", initializePanel);\n"
                + "    } else {\n"
                + "        initializePanel();\n"
                + "    }\n"
                + "}());\n");
        test.setHTMLComponent("<div class=\"herz-overlay\">\n"
                + "    <div id=\"dragBox\">\n"
                + "        <div id=\"dragHandle\">Color Panel</div>\n"
                + "\n"
                + "        <div class=\"panelContent\">\n"
                + "            <label for=\"textInput\">Text</label>\n"
                + "            <input id=\"textInput\" type=\"text\" placeholder=\"Enter text\">\n"
                + "\n"
                + "            <button id=\"myButton\" type=\"button\">Click me</button>\n"
                + "\n"
                + "            <label for=\"opacitySlider\">\n"
                + "                Translucency: <span id=\"opacityValue\">65%</span>\n"
                + "            </label>\n"
                + "            <input\n"
                + "                id=\"opacitySlider\"\n"
                + "                type=\"range\"\n"
                + "                min=\"10\"\n"
                + "                max=\"100\"\n"
                + "                value=\"65\"\n"
                + "            >\n"
                + "\n"
                + "            <label for=\"blurSlider\">\n"
                + "                Blur: <span id=\"blurValue\">16px</span>\n"
                + "            </label>\n"
                + "            <input\n"
                + "                id=\"blurSlider\"\n"
                + "                type=\"range\"\n"
                + "                min=\"0\"\n"
                + "                max=\"40\"\n"
                + "                value=\"16\"\n"
                + "            >\n"
                + "\n"
                + "            <div class=\"exampleText\">\n"
                + "                Used for testing functionalities of CSS in Eagler,\n"
                + "                Add more content here as needed.\n"
                + "            </div>\n"
                + "\n"
                + "            <div id=\"palette\" aria-label=\"Color palette\">\n"
                + "                <button type=\"button\" class=\"color active\" data-color=\"#4f46e5\" style=\"--swatch:#4f46e5\" title=\"Indigo\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#7c3aed\" style=\"--swatch:#7c3aed\" title=\"Purple\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#db2777\" style=\"--swatch:#db2777\" title=\"Pink\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#dc2626\" style=\"--swatch:#dc2626\" title=\"Red\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#ea580c\" style=\"--swatch:#ea580c\" title=\"Orange\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#ca8a04\" style=\"--swatch:#ca8a04\" title=\"Yellow\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#16a34a\" style=\"--swatch:#16a34a\" title=\"Green\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#0d9488\" style=\"--swatch:#0d9488\" title=\"Teal\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#0284c7\" style=\"--swatch:#0284c7\" title=\"Blue\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#334155\" style=\"--swatch:#334155\" title=\"Slate\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#111827\" style=\"--swatch:#111827\" title=\"Black\"></button>\n"
                + "                <button type=\"button\" class=\"color\" data-color=\"#f1f5f9\" style=\"--swatch:#f1f5f9\" title=\"White\"></button>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </div>\n"
                + "</div>\n");
        
        test.flush();

        client.getClientAPI().getWebGUIPlatform().addGUI(test);
    }
}
